[22-10-28 01:51:43,39]main.py:(17)-DEBUG - 1666902103.039889
[22-10-28 01:51:43,40]main.py:(19)-INFO - Log aggregation started
[22-10-28 01:51:43,40]main.py:(20)-INFO - ******************************
[22-10-28 01:51:43,40]main.py:(23)-DEBUG - Number of arguments passed is 3
[22-10-28 01:51:43,40]main.py:(26)-DEBUG - Arguments passed are : 9845000012 and 20220923
[22-10-28 01:51:43,40]/UMAR/python/automation/log_aggregator/input_validation.py:(24)-DEBUG - msisdn entered is valid : 9845000012
[22-10-28 01:51:43,46]/UMAR/python/automation/log_aggregator/input_validation.py:(39)-DEBUG - Transaction date entered is valid : 20220923
[22-10-28 01:51:43,291]main.py:(39)-DEBUG - Tomcat path initialized
[22-10-28 01:51:43,518]main.py:(47)-DEBUG - Prism path initialized
[22-10-28 01:51:43,753]/UMAR/python/automation/log_aggregator/tlog.py:(24)-DEBUG - Prism tlog path exists
[22-10-28 01:51:43,976]/UMAR/python/automation/log_aggregator/tlog_parser.py:(26)-DEBUG - Tlog record found for 9845000012
[22-10-28 01:51:43,976]/UMAR/python/automation/log_aggregator/tlog_parser.py:(28)-DEBUG - Parsing tlog file
[22-10-28 01:51:43,977]/UMAR/python/automation/log_aggregator/log_processor.py:(26)-DEBUG - Prism tlog parsed successfully
[22-10-28 01:51:43,977]/UMAR/python/automation/log_aggregator/daemonlog_parser.py:(27)-DEBUG - Parsing prism daemon log
[22-10-28 01:51:43,984]/UMAR/python/automation/log_aggregator/daemonlog_parser.py:(41)-DEBUG - Getting prismD log for the issue thread : WORKER_76_178971
[22-10-28 01:51:44,219]/UMAR/python/automation/log_aggregator/daemon_log.py:(24)-DEBUG - Prism daemon log path exists
[22-10-28 01:52:12,620]main.py:(65)-INFO - Log aggregation finished
[22-10-28 01:52:12,620]main.py:(66)-INFO - **********************************
[22-10-28 01:52:12,620]main.py:(78)-DEBUG - 1666902132.620771
[22-10-28 01:52:12,620]main.py:(81)-DEBUG - Total time taken 29.58088183403015
